# Generated by Django 3.2.5 on 2021-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('idol', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
